name: "Terraform Init"
description: "Runs a Terraform Init"
inputs:
  terraform_version:
    required: true
    type: string
  terraform_api:
    required: false
    type: string
  workspace:
    required: false
    type: string
  varfile:
    required: false
    type: string
  setup_terraform:
    type: boolean
    default: false
  terraform_init:
    type: boolean
    default: false
  state_bucket:
    type: string
    required: false
  state_region:
    type: string
    required: false
  state_prefix:
    type: string
    required: false
  state_dynamodb_table:
    type: string
    required: false
  init_args:
    type: string
    required: false
  commit_sha:
    required: false
    type: string
  cache_bucket:
    required: false
    type: string
    default: image-pipeline-assets

outputs:
  commit_sha:
    description: "Commit SHA"
    value: ${{ steps.checkout.outputs.commit }}
  s3_upload_path:
    description: "S3 Path for .terraform directory
    value: ${{ steps.s3_upload_path.outputs.s3_upload_path }}
  
runs:
  using: "composite"
  steps:
    - uses: CSVD/gh-actions-checkout@v4
      id: checkout
      with:
        ref: ${{ inputs.commit_sha == '' && github.sha || inputs.commit_sha }}
        persist-credentials: false

    - name: generate uuid
      id: uuid
      shell: bash
      run: |
        uuid=$(cat /proc/sys/kernel/random/uuid)
        echo UUID: ${uuid}
        echo uuid=${uuid} >> $GITHUB_OUTPUT
    
    - name: Setup Terraform
      uses: CSVD/gh-actions-setup-terraform@v2
      if: ${{ inputs.setup_terraform && env.TFE_TOKEN != '' }}
      with:
        terraform_version: ${{ inputs.terraform_version }}
        cli_config_credentials_token: ${{ env.TFE_TOKEN }}
        cli_config_credentials_hostname: ${{ inputs.terraform_api }}
 
    - name: Setup Terraform
      uses: CSVD/gh-actions-setup-terraform@v2
      if: ${{ inputs.setup_terraform && env.TFE_TOKEN == '' }}
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Set Workspace
      if: ${{ inputs.workspace != '' }}
      shell: bash
      run: |
        echo "TF_WORKSPACE=${{ inputs.workspace }}" >> $GITHUB_ENV

    - name: Terraform Init
      id: init_state
      if: ${{ inputs.terraform_init && inputs.state_bucket != '' }}
      shell: bash
      run: |
        terraform init -upgrade ${{ inputs.init_args }} \
        -backend-config="bucket=${{ inputs.state_bucket }}" \
        -backend-config="key=${{ inputs.state_prefix }}" \
        -backend-config="region=${{ inputs.state_region }}" \
        -backend-config="dynamodb_table=${{ inputs.dynamodb_table }}" 
    
    - name: Terraform Init
      id: init_no_state
      if: ${{ inputs.terraform_init && inputs.state_bucket == '' }}
      shell: bash
      run: |
        terraform init -upgrade ${{ inputs.init_args }}

    - uses: CSVD/s3-upload@main
      name: Upload .terraform
      if: ${{ inputs.workspace != '' }}
      with:
        source: .terraform
        bucket: image-pipeline-assets
        archive: true
        key: ${{ github.repository }}/${{ inputs.workspace }}/${{ steps.uuid.outputs.uuid }}/terraform-dir
        
    - uses: CSVD/s3-upload@main
      name: Upload .terraform
      if: ${{ inputs.workspace == '' }}
      with:
        source: .terraform
        bucket: image-pipeline-assets
        archive: true
        key: ${{ github.repository }}/${{ steps.uuid.outputs.uuid  }}/terraform-dir
    
    - uses: CSVD/s3-upload@main
      name: Upload Terraform Lock File (Non-Workspace)
      if: ${{ inputs.workspace != '' }}
      with:
        source: .terraform.lock.hcl
        bucket: image-pipeline-assets
        archive: false
        key: ${{ github.repository }}/${{ inputs.workspace }}/${{ steps.uuid.outputs.uuid }}/terraform.lock.hcl
      
    - uses: CSVD/s3-upload@main
      name: Upload Terraform Lock File (Workspace)
      if: ${{ inputs.workspace == '' }}
      with:
        source: .terraform.lock.hcl
        bucket: image-pipeline-assets
        archive: false
        key: ${{ github.repository }}/${{ steps.uuid.outputs.uuid }}/terraform.lock.hcl
        
    
    - name: set s3 path (workspace)
      shell: bash
      if: ${{ inputs.workspace == '' }}
      run: echo "s3_path_workspace=${{ github.repository }}/${{ steps.uuid.outputs.uuid  }}" >> $GITHUB_ENV
      
    - name: set s3 path (non-workspace)
      shell: bash
      if: ${{ inputs.workspace != '' }}
      run: echo "s3_path_non_workspace=${{ github.repository }}/${{ inputs.workspace }}/${{ steps.uuid.outputs.uuid }}" >> $GITHUB_ENV
        
    - name: set output path
      id: s3_upload_path
      shell: bash
      run:  echo "s3_upload_path=${{ inputs.workspace == '' && env.s3_path_non_workspace || env.s3_path_workspace }}" >> $GITHUB_OUTPUT
